// This file is generated by Slice Machine. Update with care!

import ContactForm from './ContactForm';
import Newsletter from './Newsletter';

export {
	ContactForm,
	Newsletter
};

export const components = {
	contact_form: ContactForm,
	newsletter: Newsletter
};
